service: ow-bq-integration-api

plugins:
  - serverless-certificate-creator
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-domain-manager
  - serverless-add-api-key
  - serverless-dotenv-plugin
  - serverless-prune-plugin

custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    dev: ow-bigquery-integration-api.<your-dev-domain>
    prod: ow-bigquery-integration-api.<your-prod-domain>
  hostedZoneNames:
    dev: <your-dev-domain>.
    prod: <your-prod-domain>.
  pythonRequirements:
    dockerizePip: true
    dockerFile: Dockerfile-SLS
    usePipenv: false
  apiKeys:
    dev:
      - name: OwBigQueryIntegrationAPIDevKey
        value: <your-api-key-dev>
    prod:
      - name: OwBigQueryIntegrationAPIProdKey
        value: <your-api-key-prod>
  wsgi:
    app: app.main:app
    packRequirements: false
  customCertificate:
    hostedZoneNames: ${self:custom.hostedZoneNames.${self:custom.stage}}
    certificateName: ${self:custom.domains.${self:custom.stage}}
    region: ${self:provider.region}
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    certificateName: ${self:custom.domains.${self:custom.stage}}
    basePath: "api"
    endpointType: regional
    stage: ${self:provider.stage}
    createRoute53Record: true
    autoDomain: true
  dotenv:
    basePath: app/envs/

provider:
  name: aws
  runtime: python3.10
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - execute-api:Invoke
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - execute-api:ManageConnections
      Resource: '*'
  timeout: 30
  lambdaHashingVersion: 20201221


package:
  exclude:
    - ./.vscode/
    - ./envs/**
    - ./notebooks/
    - ./terraform/
    - ./node_modules/
    - ./tests/
    - ./Dockerfile
    - ./docker-compose.yml
    - ./package.json
    - ./package-lock.json
    - ./poetry.lock
    - ./pyproject.toml
    - ./serverless.yml
    - ./README.md
    - ./.gitignore
    - ./.venv

functions:
  application:
    handler: app.main.handler
    events:
      - http:
          path: /{path+}
          method: ANY
          cors: true
